name: Build Documentation

on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Should match .readthedocs.yaml

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/docs.txt
        pip install .

    - name: Build Sphinx documentation
      run: |
        sphinx-build -b html docs docs/_build/html -W --keep-going
        # -W turns warnings into errors
        # --keep-going ensures all errors are reported